version: '3'

services:
  nginx:
    container_name: main-server
    image: nginx
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www/html
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - php
    networks:
      - symfony

  php:
    container_name: blog-app
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      APP_ENV: dev
      DATABASE_URL: mysql://root:root@mysql:3306/symfony_db?serverVersion=5.7
    volumes:
    - .:/var/www/html
    depends_on:
      - mysql
    networks:
      - symfony

  mysql:
    container_name: database
    image: mysql
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 4406:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - symfony

networks:
  symfony: